version: '3.8'

services:
  frontend:
    image: w8sckcw8g4ok4s48c4ss4w8c-frontend
    container_name: best-chauffeurs-frontend
    labels:
      caddy: best-chauffeurs.com
      caddy.reverse_proxy: "{{upstreams 3000}}"
    expose:
      - "3000"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:5000}
      - SERVICE_FQDN_FRONTEND=${SERVICE_FQDN_FRONTEND:-best-chauffeurs.com}
    restart: unless-stopped
    networks:
      - caddy

networks:
  caddy:
    external: true
